### ISSUE TITLE
new_counting_hash() takes at most 3 arguments (4 given)

### ISSUE THREAD

**Issue by sjackman** [mjsull/Contiguity#17]
I saw the following error after File -> Create CAG file

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/bin/contiguity", line 2817, in edge_thread
    abort = self.get_nmer_freq_khmer()
  File "/usr/local/bin/contiguity", line 3445, in get_nmer_freq_khmer
    self.ht = khmer.new_counting_hash(nmersize, ht_size, ht_n, n_threads) # HT_size, number ht, threads
TypeError: new_counting_hash() takes at most 3 arguments (4 given)
```

**Comment by mjsull** [comment]
Cheers, Khmer removed threading - Contiguity no longer needs to provide khmer with a number of threads argument.

Will push changes to PyPI ASAP.
