### ISSUE TITLE
AttributeError: 'module' object has no attribute 'new_counting_hash'

### ISSUE THREAD

**Issue by cytang19** [mjsull/Contiguity#21]
Hi Mitchell,

I tried to create CAG file and came to this error. I am lost. Do you have any idea what might be my problem? Is it the issue with the khmer? I installed it using easy_install khmer and it's version 2.0. Sorry if my issue is not relevant to be posted here. 

Cheers,
Cheng

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/data/chengyee/bin/anaconda/lib/python2.7/threading.py", line 810, in __                                  bootstrap_inner
    self.run()
  File "/data/chengyee/bin/anaconda/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "Contiguity.py", line 2883, in edge_thread
    abort = self.get_nmer_freq_khmer()
  File "Contiguity.py", line 3510, in get_nmer_freq_khmer
    self.ht = khmer.new_counting_hash(nmersize, ht_size, ht_n) # HT_size, number                                   ht, threads
AttributeError: 'module' object has no attribute 'new_counting_hash'

**Comment by cytang19** [comment]
I suspect there is no more new_counting_hash function in the latest version of khmer? Correct me if I'm wrong.

**Comment by cytang19** [comment]
Installed khmer ver 1.3 as recommended and issue is solved.
